/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -T --shadows
Author: SantMax1.0 (https://sketchfab.com/SantMax1.0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pac-man-ghost-blinky-358541bc9bb846fabfe3d664a0b77a70
Title: Pac-man Ghost Blinky
*/
import { useControls } from 'leva'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Blinky() {
  const { nodes, materials } = useGLTF('pac-man_ghost_blinky/scene-transformed.glb')
  // const { scale, position } = useControls("Blinky", {
  //   scale: {
  //     value: 0.02,
  //     min: 0.01,
  //     max: 0.05,
  //     step: 0.01,
  //   },
  //   position: [ -0.4 , -1.15 , 0 ]
  // })

  return (
    <group dispose={null} scale={0.02} position={[ -0.4, -1.15, 0 ]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 20]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_36} />
          <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_36} />
          <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_36} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
