/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -T --shadows
Author: SantMax1.0 (https://sketchfab.com/SantMax1.0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pac-man-ghost-clyde-2e3562b101ce41abb2a3e9d1508e9f03
Title: Pac-man Ghost Clyde
*/
import { useControls } from 'leva'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Clyde() 
{
  const { nodes, materials } = useGLTF('pac-man_ghost_clyde/scene-transformed.glb')
  // const { scale, position } = useControls("Clyde", {
  //   scale: {
  //     value: 0.02,
  //     min: 0.01,
  //     max: 0.09,
  //     step: 0.01,
  //   },
  //   position: [ 1 , -0.6 , 0 ]
  // })

  return (
    <group dispose={null} scale={0.02} position={[ 1, -0.6, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 20]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_18} />
          <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_18} />
          <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_18} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
