/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -T --shadows
Author: SantMax1.0 (https://sketchfab.com/SantMax1.0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pac-man-ghost-inky-b6b65cc55e1b4cfdb64e18edc133f8fd
Title: Pac-man Ghost Inky
*/
import { useControls } from 'leva'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Inky() {
  const { nodes, materials } = useGLTF('pac-man_ghost_inky/scene-transformed.glb')

  return (
    <group dispose={null} scale={0.02} position={[ -2 , -0.6 , 0 ]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 20]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.VoxMaterial_181} />
          <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.VoxMaterial_181} />
          <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.VoxMaterial_181} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
