/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -T --shadows
Author: Luall_Studio (https://sketchfab.com/luall_studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pacman-animated-e5e8dfb614da4fa69182f252fa4274a8
Title: Pacman animated
*/
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Pacman() 
{
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('pacman/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  // Animation
  useEffect(() => {
    actions.Eating.play();
  }, [])

  return <>
      <group ref={group} dispose={null} position={[0, -10, -60]}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="b6d5103afa454127a46ff4e177a0541ffbx" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_2">
                <group name="RootNode">
                  <group name="Arma����o" rotation={[-Math.PI / 2, 0, 0]} scale={13}>
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Pacman} skeleton={nodes.Object_9.skeleton} receiveShadow castShadow/>
                        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Negro} skeleton={nodes.Object_10.skeleton} receiveShadow castShadow/>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
  </>
}

useGLTF.preload('/scene-transformed.glb')
